postgres:
  image: postgres
  restart: always

  ports:
    - 35432:5432

  volumes:
    - ./volumes/postgres:/var/lib/postgresql/data

php:
  build: ./emlo-edit-php
  restart: always

  ports:
    - 80:80

  links:
    - postgres

  volumes:
    -  ./docker-exporter/exporter/exports:/var/www/html/exports
    -  ./docker-exporter/exporter/exporter_data:/var/www/exporter/exporter_data

    - ./volumes/csv:/csv

exporter:
  build: ./docker-exporter
  restart: always

  links:
    - postgres

  volumes:
    -  ./docker-exporter/exporter/exports:/usr/src/app/exports
    -  ./docker-exporter/exporter/exporter_data:/usr/src/app/exporter_data

