postgres:
  build: ./docker-postgres
  restart: always

  ports:
    - 32345:5432

  volumes:
    - ./volumes/postgres:/var/lib/postgresql/data

rabbitmq:
  image: rabbitmq:3-alpine
  restart: always

php:
  build: ./emlo-edit-php
  restart: always

  #ports:
  #  - 8080:80

  links:
    - postgres
    - rabbitmq
    - uploadermongo

  env_file:
    - docker-compose.php.env

  volumes:
    -  ./emlo-edit-php-helper/exporter/exports:/var/www/html/exports
    -  ./emlo-edit-php-helper/exporter/exporter_data:/var/www/exporter/exporter_data

    - ./volumes/csv:/csv
    - ./volumes/ssh:/root/.ssh

    - ./volumes/uploader:/uploader
    - ./volumes/tweaker:/tweaker

exporter:
  build: ./emlo-edit-php-helper
  restart: always

  links:
    - postgres
    - rabbitmq

  volumes:
    -  ./emlo-edit-php-helper/exporter/exports:/usr/src/app/exports
    -  ./emlo-edit-php-helper/exporter/exporter_data:/usr/src/app/exporter_data

    - ./emlo-edit-php-helper/tweaker/resources:/usr/src/tweaker/resources

    - ./volumes/tweaker:/tweaker_data

uploader:
  build: ./docker-uploader
  restart: always

  links:
    - postgres
    - rabbitmq
    - uploadermongo

  volumes:
    - ./volumes/uploader:/uploader

uploadermongo:
  image: mongo
  restart: always

nginx:
  build: ./nginx
  restart: always

  links:
    - php

  volumes:
    -  ../resources:/static

  ports:
    - 80:80
    - 443:443
    # - 3000:3000
