postgres:
  image: postgres

  ports:
    - 45432:5432

  volumes:
    - ./volumes/postgres:/var/lib/postgresql/data

php:
  build: ./emlo-edit-php

  ports:
    - 80:80

  links:
    - postgres

  volumes:
    -  ./docker-exporter/exporter/exports:/var/www/html/exports
    -  ./docker-exporter/exporter/exporter_data:/var/www/exporter/exporter_data

    - ./emlo-edit-php/interface:/var/www/html
    - ./emlo-edit-php/core:/var/www/core

exporter:
  build: ./docker-exporter

  links:
    - postgres

  volumes:
    -  ./docker-exporter/exporter/exports:/usr/src/app/exports
    -  ./docker-exporter/exporter/exporter_data:/usr/src/app/exports/exporter_data

    -  ./docker-exporter/exporter:/usr/src/app