postgres:
  build: ./docker-postgres

  ports:
    - 45432:5432

  volumes:
    - ./volumes/postgres:/var/lib/postgresql/data

rabbitmq:
  image: rabbitmq:3-management-alpine

  ports:
    - 5672:5672
    - 15672:15672


php:
  build: ./emlo-edit-php

  ports:
    - 8080:80

  links:
    - postgres
    - rabbitmq
    - uploadermongo

  env_file:
    - docker-compose.php.env

  volumes:
    # File links between this and exporter
    -  ./emlo-edit-php-helper/exporter/exports:/var/www/html/exports
    -  ./emlo-edit-php-helper/exporter/exporter_data:/var/www/exporter/exporter_data

    - ./volumes/csv:/csv
    - ./volumes/ssh:/root/.ssh

    # File links between this and uploader
    - ./volumes/uploader:/uploader

    # File links between this and exporter (tweaker)
    - ./volumes/tweaker:/tweaker

    # To make development easier
    - ./emlo-edit-php/interface:/var/www/html
    - ./emlo-edit-php/core:/var/www/core


exporter:
  build: ./emlo-edit-php-helper

  links:
    - postgres
    - rabbitmq

  volumes:
    # File links between this and php
    -  ./emlo-edit-php-helper/exporter/exports:/usr/src/app/exports
    -  ./emlo-edit-php-helper/exporter/exporter_data:/usr/src/app/exporter_data

    # File links between this and php
    -  ./volumes/tweaker:/tweaker_data

    # overruled by dev section - ./emlo-edit-php-helper/tweaker/resources:/usr/src/tweaker/resources

    # To make development easier
    -  ./emlo-edit-php-helper/exporter:/usr/src/app
    -  ./emlo-edit-php-helper/tweaker:/usr/src/tweaker

uploader:
  build: ./docker-uploader

  links:
    - postgres
    - rabbitmq
    - uploadermongo

  volumes:
    # File links between this and exporter
    - ./volumes/uploader:/uploader

    # To make development easier
    -  ./docker-uploader/uploader:/usr/src/app

uploadermongo:
  image: mongo
  ports:
    - 27019:27017

nginx:
  build: ./nginx

  links:
    - php

  volumes:
    -  ./static:/static

  ports:
    - 80:80
    - 443:443
    - 3000:3000