postgres:
  image: postgres:9.6

  ports:
    - 45432:5432

  volumes:
    - ./volumes/postgres:/var/lib/postgresql/data


php:
  build: ./emlo-edit-php

  ports:
    - 8080:80

  links:
    - postgres

  env_file:
    - docker-compose.php.env

  volumes:
    -  ./docker-exporter/exporter/exports:/var/www/html/exports
    -  ./docker-exporter/exporter/exporter_data:/var/www/exporter/exporter_data

    - ./volumes/csv:/csv
    - ./volumes/ssh:/root/.ssh

    # Dev only
    - ./emlo-edit-php/interface:/var/www/html
    - ./emlo-edit-php/core:/var/www/core


exporter:
  build: ./docker-exporter

  links:
    - postgres

  volumes:
    -  ./docker-exporter/exporter/exports:/usr/src/app/exports
    -  ./docker-exporter/exporter/exporter_data:/usr/src/app/exporter_data

    -  ./docker-exporter/exporter:/usr/src/app


nginx:
  build: ./nginx

  links:
    - php

  ports:
    - 80:80
    - 443:443
    - 3000:3000