postgres:
  build: ./docker-postgres

  ports:
    - 45432:5432

  volumes:
    - ./volumes/postgres:/var/lib/postgresql/data

rabbitmq:
  image: rabbitmq:3-management-alpine

  ports:
    - 5672:5672
    - 15672:15672


php:
  build: ./emlo-edit-php

  ports:
    - 8080:80

  links:
    - postgres
    - rabbitmq
    - uploadermongo

  env_file:
    - docker-compose.php.env

  volumes:
    -  ./docker-exporter/exporter/exports:/var/www/html/exports
    -  ./docker-exporter/exporter/exporter_data:/var/www/exporter/exporter_data

    - ./volumes/csv:/csv
    - ./volumes/ssh:/root/.ssh

    - ./volumes/uploader:/uploader

    # Dev only
    - ./emlo-edit-php/interface:/var/www/html
    - ./emlo-edit-php/core:/var/www/core


exporter:
  build: ./docker-exporter

  links:
    - postgres

  volumes:

    -  ./docker-exporter/exporter/exports:/usr/src/app/exports
    -  ./docker-exporter/exporter/exporter_data:/usr/src/app/exporter_data

    -  ./docker-exporter/exporter:/usr/src/app

    # Dev only
    -  ./docker-exporter/tweaker:/usr/src/tweaker

uploader:
  build: ./docker-uploader

  links:
    - postgres
    - rabbitmq
    - uploadermongo

  volumes:
    - ./volumes/uploader:/uploader

    # Dev only
    -  ./docker-uploader/uploader:/usr/src/app

uploadermongo:
  image: mongo

nginx:
  build: ./nginx

  links:
    - php

  volumes:
    -  ./static:/static

  ports:
    - 80:80
    - 443:443
    - 3000:3000